POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"Pepe puto la concha de tu madre Sarmiento",
    "important": false
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{

}